version: '3.9'
services: 
  #mongodb services
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - 2717:27017

  # Node API service
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/user/social-app
    environment: 
      PORT: 3000
      MONGO_URL : mongodb://mongodb:27017
      jwt_key : secretoken
    depends_on: 
      - mongodb

volumes: 
  mongodb_data: {}